M48
; DRILL file {KiCad (6.0.10)} date Wed Apr 12 11:10:31 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-12T11:10:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X1.8573Y-1.5602
X2.0482Y-1.5602
T2
X1.8455Y-1.4409
X2.06Y-1.4409
T0
M30
