M48
; DRILL file {KiCad (6.0.10)} date Tue Jan 17 15:14:55 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-17T15:14:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X1.8085Y-1.5644
X1.9994Y-1.5644
T2
X1.7967Y-1.4451
X2.0112Y-1.4451
T0
M30
