M48
; DRILL file {KiCad (6.0.10)} date Tue Jan 17 16:12:40 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-17T16:12:40-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X45.935Y-39.735
X50.785Y-39.735
T2
X45.635Y-36.705
X51.085Y-36.705
T0
M30
