name: Build firmware

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]


jobs:
  build-firmware:
    runs-on: ubuntu-latest
    name: Build firmware
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build --pull --build-arg APT_MIRROR="http://azure.archive.ubuntu.com/ubuntu/"

      - name: Run docker container
        run: docker compose up --exit-code-from buildfirmware

      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dds-sweeper-firmware-${{ github.sha }}
          path: |
            build/dds-sweeper/*.uf2
            LICENSE

  github-release:
    name: Github Release
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && contains(github.ref, '/tags') && github.repository_owner == 'QTC-UMD')
    needs: [build-firmware]
    permissions:
      packages: read
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dds-sweeper-firmware-${{ github.sha }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          generate_release_notes: true
          files: |
            LICENSE
            dds-sweeper.uf2